name: First interaction

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write  # Tarvitaan, jotta voidaan kommentoida PR:채채n

jobs:
  greet-first-pr:
    runs-on: ubuntu-latest
    steps:
      - name: First interaction
        uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Onnittelut ensimm채isest채 pull requestista!
